name: PHP CI

on:
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate-mergable:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Validate Mergable"
        run: git merge origin/master --no-commit --ff-only

  render-php:
    needs: validate-mergable
    runs-on: ${{ matrix.operating-system }}

    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.0", "8.1", "8.2"]
        phpunit-versions: ["latest"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: phpunit:${{ matrix.phpunit-versions }}

      - name: "Composer State"
        run: composer update --no-install --with-all-dependencies

      - name: "Composer Name Hash"
        id: composer-hash
        uses: KEINOS/gh-action-hash-for-cache@main
        with:
          path: ./composer.lock

      - name: "Caching"
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ steps.composer-hash.outputs.hash }}
          restore-keys: composer-${{ steps.composer-hash.outputs.hash }}

      - name: "Install Dependencies"
        if: ${{ steps.cache-composer.outputs.cache-hit != 'true' }}
        run: composer install

      - name: "Linux: Restore Vendor Executable"
        if: matrix.operating-system == 'ubuntu-latest'
        run: chmod -R 0755 vendor

      - name: "PHPUnit"
        run: ./vendor/bin/phpunit

      - name: "Coverage"
        run: echo "$(cat ./.phpunit/coverage.txt)"

      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: .github/coverage.svg
          # push badge later on
          push_badge: false

      - name: Git push badges to image-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .github
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
