name: PHP CI
on:
  pull_request:
    branches:
      - "master"
  workflow_dispatch:
jobs:
  render-php:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest"]
        php-versions: ["7.0", "7.4", "8.0", "8.1"]
        phpunit-versions: ["latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate up to date with Master
        run: git merge origin/master --no-commit --ff-only
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: phpunit:${{ matrix.phpunit-versions }}
      - name: "Composer update and install"
        run: composer install
      - name: "PHPUnit tests"
        run: ./vendor/bin/phpunit
